In [4]:
from sklearn import datasets

In [5]:
data = datasets.load_iris()

In [6]:
import numpy as np

In [7]:
x = np.array([
    [1,2],
    [3,4]
])

In [8]:
x

array([[1, 2],
       [3, 4]])

In [9]:
x.ndim

2

In [10]:
x = np.array(12)

#Scalar Tensor mean only one number in a tensor
it is a 0-dimensional tensor we can use x.ndim to see

In [11]:
x = np.array([12,3,6,14])

In [12]:
x.ndim

1

In [13]:
x.shape

(4,)

In [14]:
x

array([12,  3,  6, 14])

In [15]:
from keras.datasets import mnist

Using TensorFlow backend.
/Applications/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [16]:
(train_data, train_label),(test_data, test_label) = mnist.load_data()

In [17]:
train_data.shape

(60000, 28, 28)

In [18]:
# each 28 * 28 is a 2 dim array
# so train_data[0] will display first numberdata

In [19]:
len(train_data)

60000

In [20]:
len(train_data[0])

28

In [21]:
from keras import models

In [22]:
from keras import layers

In [23]:
network = models.Sequential()

In [24]:
network.add(
    layers.Dense(
        512, activation='relu', input_shape=(28*28,)))

In [25]:
# a dense layer that fully connected to each other

In [26]:
network.add(
    layers.Dense(
        10,activation='softmax'))

In [27]:
# total of two layers, this last layer has a output of 10
# which is 10 label that we have

In [28]:
# compliation Step

In [29]:
network.compile(
    optimizer='rmsprop',
    loss='categorical_crossentropy',
    metrics=['accuracy'])

In [30]:
# Please understand this paraemter later

In [31]:
train_data = train_data.reshape((60000,28*28))

In [32]:
# Reshape it to what the network expects

In [33]:
train_data.shape

(60000, 784)

In [34]:
train_data = train_data.astype('float32')/255

In [35]:
# change type from unit8 0-255 to
#float32 0-1 ex 0.123212

In [36]:
test_data = test_data.reshape((10000, 28*28))

In [37]:
test_data = test_data.astype('float32')/255

In [38]:
from keras.utils import to_categorical

In [39]:
train_label = to_categorical(train_label)

In [40]:
train_label[0]

array([ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.])

In [46]:
network.fit(
train_data,train_label,epochs=5,batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 6s 101us/step - loss: 0.0200 - acc: 0.9940
Epoch 2/5
60000/60000 [==============================] - 6s 96us/step - loss: 0.0151 - acc: 0.9958
Epoch 3/5
60000/60000 [==============================] - 6s 99us/step - loss: 0.0111 - acc: 0.9969
Epoch 4/5
60000/60000 [==============================] - 6s 96us/step - loss: 0.0086 - acc: 0.9978
Epoch 5/5
60000/60000 [==============================] - 6s 95us/step - loss: 0.0074 - acc: 0.9979


In [58]:
image4 = train_data[4]

In [59]:
image4

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.  

In [77]:
train_data.dtype

dtype('float32')